### ISSUE TITLE
Let us change port

### ISSUE THREAD

**Issue by aicynide** [Stremio/server-docker#11]

**Comment by TRtomasz** [comment]
Please create issues with actual content inside, instead just title.

**Comment by jaruba** [comment]
@TRtomasz it is obvious enough, he wants to change the port of the docker server

**Comment by TRtomasz** [comment]
@aicynide I'm just guessing here what you wanted you can change exposed poet by modifying '-p' parameter like described here https://stackoverflow.com/questions/62125794/docker-run-p-what-are-this-two-port-numbers-and-what-they-represents

**Comment by aicynide** [comment]
@TRtomasz I'm aware about docker -p port. I'm asking about server.js port changing from server-settings.json

**Comment by jaruba** [comment]
@aicynide why do you need to change server.js port if you use docker?

**Comment by aicynide** [comment]
@jaruba in stremio-service also, port can't be changed. Please let us change port
