### ISSUE TITLE
Streaming server is not available

### ISSUE THREAD

**Issue by JustWolfii** [Stremio/server-docker#12]
I have an issue where if I run the server, it appears to run as when I enter the IP address and the port, it redirects me to app.strem.io and sets the streaming server to the correct IP address and port, but when I go into Settings > Streaming, it says "Streaming server is not available" and I cannot play anything.

```
hls executables located ->  {
  ffmpeg: '/usr/lib/jellyfin-ffmpeg/ffmpeg',
  ffsplit: null,
  ffprobe: '/usr/lib/jellyfin-ffmpeg/ffprobe'
}
Using app path -> /root/.stremio-server
Cannot update settings ENOENT: no such file or directory, open '/root/.stremio-server/server-settings.json'
Enabling casting...
(node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
EngineFS server started at http://127.0.0.1:11470
hls-converter - Initiating tests for hardware accelerated transcoding support, possible options: qsv-linux,nvenc-linux,vaapi-renderD128
hls-converter - Testing video hw accel for profile: qsv-linux
EngineFS HTTPS endpoint at https://local.strem.io:12470
-> GET /hlsv2/11470-qsv-linux-video-hevc.mkv/video0.m3u8?mediaURL=http%3A%2F%2F127.0.0.1%3A11470%2Fsamples%2Fhevc.mkv&profile=qsv-linux&maxWidth=1200 
-> GET /samples/hevc.mkv bytes=0-
-> GET /samples/hevc.mkv 
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (internal/errors.js:322:7)
    at Socket.onclose (internal/streams/end-of-stream.js:121:38)
    at Socket.emit (events.js:412:35)
    at Socket.emit (domain.js:475:12)
    at Pipe.<anonymous> (net.js:686:12) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
-> GET /hlsv2/11470-qsv-linux-video-hevc.mkv/destroy 
hls-converter 11470-qsv-linux-video-hevc.mkv has been requested to be destroyed
hls-converter 11470-qsv-linux-video-hevc.mkv destoyed
hls-converter - Tests failed for [video] hw accel profile: qsv-linux
hls-converter - Some tests failed for hw accel profile: qsv-linux
hls-converter - Testing video hw accel for profile: nvenc-linux
-> GET /hlsv2/11470-nvenc-linux-video-hevc.mkv/video0.m3u8?mediaURL=http%3A%2F%2F127.0.0.1%3A11470%2Fsamples%2Fhevc.mkv&profile=nvenc-linux&maxWidth=1200 
hls-converter 11470-qsv-linux-video-hevc.mkv will be destroyed due to passing concurrency of 1
-> GET /samples/hevc.mkv 
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (internal/errors.js:322:7)
    at Socket.onclose (internal/streams/end-of-stream.js:121:38)
    at Socket.emit (events.js:412:35)
    at Socket.emit (domain.js:475:12)
    at Pipe.<anonymous> (net.js:686:12) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
-> GET /hlsv2/11470-nvenc-linux-video-hevc.mkv/destroy 
hls-converter 11470-nvenc-linux-video-hevc.mkv has been requested to be destroyed
hls-converter 11470-nvenc-linux-video-hevc.mkv destoyed
hls-converter - Tests failed for [video] hw accel profile: nvenc-linux
hls-converter - Some tests failed for hw accel profile: nvenc-linux
hls-converter - Testing video hw accel for profile: vaapi-renderD128
-> GET /hlsv2/11470-vaapi-renderD128-video-hevc.mkv/video0.m3u8?mediaURL=http%3A%2F%2F127.0.0.1%3A11470%2Fsamples%2Fhevc.mkv&profile=vaapi-renderD128&maxWidth=1200 
hls-converter 11470-nvenc-linux-video-hevc.mkv will be destroyed due to passing concurrency of 1
-> GET /samples/hevc.mkv 
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (internal/errors.js:322:7)
    at Socket.onclose (internal/streams/end-of-stream.js:121:38)
    at Socket.emit (events.js:412:35)
    at Socket.emit (domain.js:475:12)
    at Pipe.<anonymous> (net.js:686:12) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
-> GET /hlsv2/11470-vaapi-renderD128-video-hevc.mkv/destroy 
hls-converter 11470-vaapi-renderD128-video-hevc.mkv has been requested to be destroyed
hls-converter 11470-vaapi-renderD128-video-hevc.mkv destoyed
hls-converter - Tests failed for [video] hw accel profile: vaapi-renderD128
hls-converter - Some tests failed for hw accel profile: vaapi-renderD128
hls-converter - Tests for hardware accelerated transcoding finished, no viable acceleration profiles detected
Resizing cache size to 2048MB from 0MB by deleting 0 files

 
hls-converter 11470-vaapi-renderD128-video-hevc.mkv is inactive, destroying it
hls-converter 11470-vaapi-renderD128-video-hevc.mkv destoyed
hls executables located ->  {
  ffmpeg: '/usr/lib/jellyfin-ffmpeg/ffmpeg',
  ffsplit: null,
  ffprobe: '/usr/lib/jellyfin-ffmpeg/ffprobe'
}
Using app path -> /root/.stremio-server
Enabling casting...
(node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
EngineFS server started at http://127.0.0.1:11470
EngineFS HTTPS endpoint at https://local.strem.io:12470

 

 ```

**Comment by psamit** [comment]
Use streaming server `http://127.0.0.1:11470` in the [web.stremio.com](https://web.stremio.com).

One issue I have found is that I am not able to access the server using an IP address(it is not accessible via <computer ip>:11470).

**Comment by JustWolfii** [comment]
> Use streaming server `http://127.0.0.1:11470` in the [web.stremio.com](https://web.stremio.com).
> 
> One issue I have found is that I am not able to access the server using an IP address(it is not accessible via :11470).

That is an issue as I'm running the server on a Linux VPS which is not in my house, so I cannot use local

**Comment by jaruba** [comment]
@JustWolfii Stremio Web will only connect to a HTTPS server if it's not from localhost, so it will only work with a SSL certificate through LAN or the internet. We offer SSL certificates to users only for LAN use, we do not officially advertise or recommend attempting to use the server outside of your LAN, it is insecure..

**Comment by JustWolfii** [comment]
> @JustWolfii Stremio Web will only connect to a HTTPS server if it's not from localhost, so it will only work with a SSL certificate through LAN or the internet. We offer SSL certificates to users only for LAN use, we do not officially advertise or recommend attempting to use the server outside of your LAN, it is insecure..

I have put the server behind a domain name with a SSL certificate and it works now. Thank you for the help!

**Comment by PDiogoVS** [comment]
@JustWolfii Can you explain how you went about enabling HTTPS and generating the certificate? There is little documentation on this

**Comment by RyanEwen** [comment]
> @JustWolfii Can you explain how you went about enabling HTTPS and generating the certificate? There is little documentation on this

You can setup an NGINX vhost that uses HTTPS and have it reverse proxy to your stremio IP using HTTP / 11470 and it'll work okay. The downside is that when users go to your stremio URL directly (eg https://mystremio.whatever.com) the web client will try to add http://mystremio.whatever.com (note the lack of an s in https) which won't work.

Instead of that I setup my NGINX vhost to reverse proxy to stremio using HTTPS / 12470, which requires you to first ask stremio to generate a local self-signed HTTPS cert, which you can do by going to `http://<your-local-stremio-server-ip>:11470/get-https?ipAddress=<your-local-stremio-server-ip>`. It will put the self-signed certs into `/root/.stremio-server` so if you are using Docker it might be a good idea to mount that as a volume so that it persists.

My NGINX config:
```
# stremio
server {
    server_name stremio.my-domain.com;

    listen 80;
    listen 443 ssl;

    ssl_certificate /letsencrypt/live/stremio.my-domain..com/fullchain.pem;
    ssl_certificate_key /letsencrypt/live/stremio.my-domain.com/privkey.pem;

    # Redirect non-https traffic to https
    if ($scheme != "https") {
        return 301 https://$host$request_uri;
    }

    proxy_buffering off;

    location / {
        proxy_pass https://192.168.2.11:12470; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

My stremio docker compose yaml:
```yaml
  stremio:
    image: stremio/server:latest
    ports:
      - 11470:11470
      - 12470:12470
    volumes:
      - ./stremio:/root/.stremio-server
```

Note: Anyone could use your server as there's no auth of any kind, so this isn't the best idea.

**Comment by rpop0** [comment]
> @JustWolfii Stremio Web will only connect to a HTTPS server if it's not from localhost, so it will only work with a SSL certificate through LAN or the internet. We offer SSL certificates to users only for LAN use, we do not officially advertise or recommend attempting to use the server outside of your LAN, it is insecure..

I don't quite understand what you mean by 'We offer SSL certificates to users only for LAN use'. I'm having the same issues as described by the reporter but my stremio server is running on a device in my local network.
