### ISSUE TITLE
Unexpected Token '<' when running container

### ISSUE THREAD

**Issue by raycekar** [Stremio/server-docker#15]
Hi, am trying to work on a custom container and am running into the following error:

![image](https://github.com/Stremio/server-docker/assets/17347780/7d425ee7-8934-4a90-bc5b-5577450820f4)

So far I have changed very little from the script except for commenting out jellyfin and adding the execution flag to the downlaod_server.sh file.

[Dockerfile.txt](https://github.com/Stremio/server-docker/files/12308372/Dockerfile.txt)
Here is the file and no changes were made to the download_server.sh.

**Comment by prom3theu5** [comment]
Same thing happened here
This is due to you not passing the server version as an argument when building the docker image

You can see why you are getting the xml error here, after overriding entrypoint:

```bash
docker run --entrypoint=bash -it stremio-server

root@078ed5e00cdf:/stremio# ls
Dockerfile  README.md  download_server.sh  server.js  setup_jellyfin_repo.sh

root@078ed5e00cdf:/stremio# cat server.js
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>server/master/desktop/server.js</Key><RequestId>V6VXYV1NXTMXR2YA</RequestId><HostId>A6gXI/Mk8kht/niCG0DSaAnwRnprLdxLwVIe+rqJJKX7eB2DfbXMnfvUJS1s3Xb9qp+hpFLfxro=</HostId></Error>root@078ed5e00cdf:/stremio#
```

**Comment by elpiel** [comment]
Please check this issue: #37 

This is due to a missing artifact when the docker container build was triggered
