### ISSUE TITLE
Support for ARM based Servers (aarch64)

### ISSUE THREAD

**Issue by ramkuar0020** [Stremio/server-docker#2]
The Image Currently seems to only works for linux/amd64.
It'd be great if it could be supported in linux/arm64/v8 
The Unofficial Stremio-Server Docker image used to support arm64 (https://github.com/sleeyax/stremio-streaming-server)
The Streaming Server Hosted Via this Unofficial Image Works For app.strem.io but shows error in the new web.stremio.com
I have the old unofficial server hosted as demo on : srv.motiaunty.tv:11470

**Comment by esteve** [comment]
@ramkuar0020 the changes in #5 should work, can you give https://hub.docker.com/r/esteve/stremio-service/tags a try and see if it works for you on an arm64? Thanks.
