### ISSUE TITLE
v4.20.9 crashes on startup and exits the container

### ISSUE THREAD

**Issue by aptalca** [Stremio/server-docker#37]
Hi, I've been using `v4.20.8` for a quite some time, and it was stable.

`v4.20.9` on the other hand crashes immediately and the container stops

I also tried a fresh container with the docker run from the readme here and here's the output:
```
$ docker run --rm -p 11470:11470 -p 12470:12470 -e NO_CORS=1 stremio/server:latest
/stremio/server.js:1
<?xml version="1.0" encoding="UTF-8"?>
^

SyntaxError: Unexpected token '<'
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
```

This is on an amd64 machine running ubuntu noble with kernel 6.1.99

Thanks

PS. Trying just `docker run --rm stremio/server:latest` with no other arguments results in the same behavior.

**Comment by Nathan-Kr** [comment]
the bundled server.js is empty
![image](https://github.com/user-attachments/assets/85775c53-9dab-4fe5-b0b6-535f3fd8b89c)

Tho the url https://dl.strem.io/server/v4.20.9/desktop/server.js is working so I assume the VERSION arg was missing during build or there was a problem on the dl server at build time.
We could benefit from a server.js file check during buildtime (http code + hash)

**Comment by yihaolee85** [comment]
I have the same problem running this on a Synology NAS. Reverting to 4.20.8 resolved the issue.

**Comment by rodrigosiviero** [comment]
same here

**Comment by alided** [comment]
Same here, spent half a day figuring out the issue with my config. Reverting to v4.20.8 seems to work.

**Comment by besoeasy** [comment]
![image](https://github.com/user-attachments/assets/e7bbdf2b-5708-48ca-978a-89a5ac1b011f)

**Comment by marty-macfly** [comment]
It seems version [4.20.11](https://hub.docker.com/layers/stremio/server/v4.20.11/images/sha256-b88114035418f77455ef3f1d7094dba37fec8f08822a670b388f8b7fa14414e3?context=explore) is suffering of the same issue.

```
SyntaxError: Unexpected token '<'
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
/stremio/server.js:1
<?xml version="1.0" encoding="UTF-8"?>
```


And [4.20.10](https://hub.docker.com/layers/stremio/server/v4.20.10/images/sha256-0794eb1fddc71f575d97360c532a4e4e273c0886c4deb0291256edddbad93b86?context=explore) also:

```
SyntaxError: Unexpected token '<'
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by rodrigosiviero** [comment]
> It seems version [4.20.11](https://hub.docker.com/layers/stremio/server/v4.20.11/images/sha256-b88114035418f77455ef3f1d7094dba37fec8f08822a670b388f8b7fa14414e3?context=explore) is suffering of the same issue.
> 
> ```
> SyntaxError: Unexpected token '<'
>     at wrapSafe (internal/modules/cjs/loader.js:1029:16)
>     at Module._compile (internal/modules/cjs/loader.js:1078:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
>     at Module.load (internal/modules/cjs/loader.js:979:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
>     at internal/main/run_main_module.js:17:47
> /stremio/server.js:1
> <?xml version="1.0" encoding="UTF-8"?>
> ```
> 
> Content of the `server.js`j:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>server/v4.20.11/desktop/server.js</Key><RequestId>QFW87W44BJNG142D</RequestId><HostId>8A7FwmthLfgVE1+emVzPp97TkuXpJnX7cOfhLPrkU771bMJsdJKWgvQbSAhHpXiZIjNTrTJrjLE=</HostId></Error>
> ```
> 
> And [4.20.10](https://hub.docker.com/layers/stremio/server/v4.20.10/images/sha256-0794eb1fddc71f575d97360c532a4e4e273c0886c4deb0291256edddbad93b86?context=explore) also:
> 
> ```
> SyntaxError: Unexpected token '<'
>     at wrapSafe (internal/modules/cjs/loader.js:1029:16)
>     at Module._compile (internal/modules/cjs/loader.js:1078:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
>     at Module.load (internal/modules/cjs/loader.js:979:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
>     at internal/main/run_main_module.js:17:47
> ```

can confirm latest version still with same error....

**Comment by aptalca** [comment]
It doesn't look like anyone at Stremio is paying attention to this repo and they don't realize that whatever automation they got going for pushing docker builds is borked.

I resorted to building locally with the following:
`docker build -t whatevernameyouwant --build-arg VERSION=v4.20.11 .`

As long as you pass the VERSION as a build arg, it will download the artifact and build a functional docker image

**Comment by jaruba** [comment]
we know the issue, it's caused by a race condition in an automation, unfortunately the people that could fix this will are not available atm, i expect a fix to be available next wednesday

**Comment by marty-macfly** [comment]
> It doesn't look like anyone at Stremio is paying attention to this repo and they don't realize that whatever automation they got going for pushing docker builds is borked.
> 
> I resorted to building locally with the following: `docker build -t whatevernameyouwant --build-arg VERSION=v4.20.11 .`
> 
> As long as you pass the VERSION as a build arg, it will download the artifact and build a functional docker image

Yes, that's what I've done to work around but in my case when I'm moving from version 4.20.8 to 4.20.11, streaming is not working anymore... Can not connect to any peer when in 4.20.8 connection and download is starting in few seconds.

**Comment by elpiel** [comment]
I've built and pushed the latest images that were effected by the human-created race condition.

We are working on fixing our release workflow to completely eliminate this issue.

Please pull the latest images and re-open the issue if you are still experiencing issue:

https://hub.docker.com/repository/docker/stremio/server/tags
