### ISSUE TITLE
SSDP error

### ISSUE THREAD

**Issue by maxcynicle** [Stremio/server-docker#6]
### Current Behavior:
Error below can be seen in logs of the container if container network is not on local LAN
```
SSDP error: {
  type: 'ssdp',
  error: {
    type: 'send',
    error: Error: send EPERM 239.255.255.250:1900
        at doSend (dgram.js:714:16)
        at defaultTriggerAsyncIdScope (internal/async_hooks.js:452:18)
        at afterDns (dgram.js:660:5)
        at processTicksAndRejections (internal/process/task_queues.js:83:21) {
      errno: -1,
      code: 'EPERM',
      syscall: 'send',
      address: '239.255.255.250',
      port: 1900
    }
  }
}
```

### Expected Behavior:
SSDP should be configurable for user to disable, especially if being used in an environment where network advertising/discovery is restricted. SSDP error above should not spam the logs and should break out if unable to proceed.

### Steps To Reproduce:
docker pull stremio/server:latest
set network to custom network
copy server.js into /stremio
run container
observe error in logs

### Environment:
**Unraid 6.11.5**
server.js obtained from https://dl.strem.io/server/v4.20.1/desktop/server.js
container is set with --net=container:passthroughvpn that is connecting to a VPN service using Wireguard for ingress/egress traffic. All network traffic is tunneled through this special container and goes through the VPN service

### Anything else:
SSDP error does not appear when network is on the host local LAN (bridge mode)
Removing SSDPDiscovery from Line 73037 in server.js is the workaround to stop the log flooding

var fs = __webpack_require__(2), path = __webpack_require__(3), tmp = __webpack_require__(389), child = __webpack_require__(20), fetch = __webpack_require__(24), pump = __webpack_require__(123), URL = (__webpack_require__(795), 
    __webpack_require__(8).URL), castingUtils = __webpack_require__(175), Discovery = __webpack_require__(796), ExternalDiscovery = __webpack_require__(797), MDNSDiscovery = __webpack_require__(802), SSDPDiscovery = __webpack_require__(811), ChromecastClient = __webpack_require__(849), DLNAClient = __webpack_require__(859), Router = __webpack_require__(82), discovery = new Discovery([ ~~SSDPDiscovery,~~ MDNSDiscovery, ExternalDiscovery ]), noop = Function.prototype;

**Comment by jaruba** [comment]
Casting can be disabled with an env var: `CASTING_DISABLED=1`
